name: Deploy & E2E

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Deploy on Zeit
        uses: marlass/now-deployment@v1
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.TOKEN_GITHUB }}
  test:
    needs: [deploy]
    name: Smoke
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # run 1 copy of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: zeit-url
        uses: marlass/now-deployment-url@master
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
      - name: Cypress smoke
        run: echo $CYPRESS_BASE_URL
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_BASE_URL: ${{ env.CYPRESS_BASE_URL }}
