name: Deploy & E2E

on: [push]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Build
        run: yarn && yarn build:core:lib && yarn build:ci:ccv2 && node ./ci-scripts/generate-vercel-project.js
        env:
          token: ${{ secrets.ZEIT_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: zeit-url
        uses: marlass/now-deployment@master
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          now-args: 'dist/storefrontapp --local-config ./now.csr.json'
  test:
    needs: [build-and-deploy]
    name: E2E tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # run 1 copy of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: zeit-url
        uses: marlass/now-deployment-url@master
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
      - name: Cypress tests
        run: yarn && cd projects/storefrontapp-e2e-cypress && yarn && echo $CYPRESS_BASE_URL && yarn run cy:run:ccv2
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_BASE_URL: ${{ env.CYPRESS_BASE_URL }}
