name: Deploy & E2E

on: [deployment_status]

jobs:
  test:
    name: E2E tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # run 1 copy of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: zeit-url
        uses: marlass/now-deployment-url@master
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
      - name: Cypress smoke
        run: echo $CYPRESS_BASE_URL
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_BASE_URL: ${{ env.CYPRESS_BASE_URL }}
