on: push
name: CI
jobs:
  breakingChangeDetectionBot:
    name: Breaking change detection bot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Breaking change detection bot
      uses: ./.github/api-extractor-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install -g yarn
    - run: yarn
    - run: yarn lint
  unit-core:
    name: Unit tests core
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install -g yarn
    - run: yarn
    - run: npm i -g @angular/cli
    - run: ng test core --watch=false --sourceMap --code-coverage --browsers=ChromeHeadless
  unit-lib:
    name: Unit tests lib
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install -g yarn
    - run: yarn
    - run: npm i -g @angular/cli
    - run: ng test storefrontlib --watch=false --sourceMap --code-coverage --browsers=ChromeHeadless
  e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install -g yarn
    - run: yarn e2e:cy:start-run-ci
